### ISSUE TITLE
path_excelfile

### ISSUE THREAD

**Issue by pdavidsonFIA** [wjwillemse/solvency2-data#3]
This isn't a bug as much as a feature request. When I use the package I adjust the code to add path_excelfile and path_zipfile to RFR_dict.
It would be need if parameter folders were read in from a config file, or passed as an optional parameter when the class is initialised.
There is also a line in def read() which effectively overwrites the path parameter - I need to comment this out to make the target path persist.

**Comment by wjwillemse** [comment]
In version 0.1.8, I added a configuration file. In the root of the package there is a solvency2_data.cfg file where you can specify the directories where to store and read the .zip and .xlsx files. This file can also be in your working directory (so it won't be overwritten when you install a new version). When you use the read() function, first it will look in your working directory for the .cfg file, otherwise it will use the .cfg from the root of the package location. You can also still use a path parameter when using the read() function.

**Comment by johalnes** [comment]
@wjwillemse the solvency2-data.cfg file is not inclueded when the package is installed by PIP. I found it here on Git in the main project folder, when it probably should be in the source folder.

Also when copied to package folder it didn't work, but worked fined when put in project folder.

**Comment by wjwillemse** [comment]
Sorry for the delay. I have changed the name of the configuration file to solvency2_data.cfg (with underscore), moved it to the source folder, and added the file name to MANIFEST.in (in order to include it in the pypi-package). Also improved the code of solvency2_data.py with Flake8 recommendations. 

It should work when the config file is in your project folder. If the config file is not in your project folder then it uses the default config file (and zip and excel are stored in the current folder from which the code is run). Hope it works.

**Comment by pdavidsonFIA** [comment]
Thanks, this did work - and thanks for accepting my pull request :)
